///|
pub extend Poly with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Poly with Default::{default}

///|
pub extend Polyveck with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Polyveck with Default::{default}

///|
pub extend Polyvecl with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Polyvecl with Default::{default}

///|
pub extend KeccakState with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend KeccakState with Default::{default}
